"""rename dpartment

Revision ID: d0964df86ce8
Revises: fa86e5f0dbee
Create Date: 2024-06-25 08:21:51.276108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0964df86ce8'
down_revision = 'fa86e5f0dbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
